return function (s)
  local r
  if s.run then
    print("Module X55 is run")
    gpio.mode(5, gpio.OUTPUT)
    gpio.write(5, s.mute)
    gpio.mode(7, gpio.OUTPUT)
    gpio.write(7, s.mute == 0 and 1 or 0)
    _Defender = s
    print(i2c.setup(0, 4, 3, i2c.SLOW))
    local mytimer = tmr.create()
    mytimer:register(1000, tmr.ALARM_SINGLE, function (t)
        dofile("Defender_X55.lua")(s)
        dofile("Defender_X55_ir.lua")
    end)
    mytimer:start()
    r=true
  end
  return r
end